 [gcp_service_account]
type = "service_account"
project_id = "onlimo"
private_key_id = "794bae89654fb94594dcaaf72966082f8481af22"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDDM24jXVINsFr0
hJV90Czrn3Ut7s7QOvBTgpVBxGtF5ApiveQQ8uVcfkorJpQo9NyA6kN6KVWPAkV1
3HfkRBRr+Cl/+g1tBRCQecngHknkEHRv4i/iN67PtEnoKqOn4FHoWF9TLbaB9pQW
2B21QJnsFv54mPya9FdaJqxPtdjx9g4qjtptUONb+nlBuFzYxCZ2XzLp7CpdyC5r
VZyDxyys40OTk07EjFdoomI1i8WZSF3/0KCEXL014SomfDtO9iCrU4d+cyzF6HCk
8VnW426sqp/QLIvkWSSvLiZdzEsxMAWSUXxRjVVerC4N5jxsEXhvnp8lNM3NvOEf
xmkezHdBAgMBAAECgf8hKxwL5k+LA+xwoBbGyhjX8MB4jZuWxm0Pw6CZDEcuGRGq
tZmLR7qxfMQdkPCcBP9y6FuO5ncjVb93x36XyvmtXv2uQU8Gt1WZNxiWfI8RsboX
SNfaGJwbrwbf7F7ip7tDP8Dy4VGhw8RmHVLu+YsuEroqw9QogFxXdTrSUJQMiPY6
bbG7hV6aYUB3IiTvQF8L9PR5nQ6lTA8dKm+Ps0dkzfEJSvvJWmWAh5xaRfmUwpO9
ZbJodsqGRgr09b3T8WDDbCnSOxshY/jtBiPgrIYOKqE6trdcH+yVYlA5/eBu7zxF
O+hdD+AXLmlWvVToLfSZV5aVvUlOyEyXti96d08CgYEA/2A1d1Hhy9pR810OZH7X
xpPnXTAo9UfpaTwNSqyBVJafr+ox7PcuB+3lvzPJwbEoIOjdpJvL3JqVXYxHNQC7
THHUATAJJa+5PK9gNE8JxEYXSZL9+NzqRBk5szTplLpVhLeR+qHQ1dZ5NBv+eM7e
ZVcfhz6g5am8PiZbunk8amcCgYEAw62RwFITRdtopDqsRHUFDq6DmFVQQkXO2k5T
zBc1IRi3TfpkNTJgLQV4S2xe+++SEPPKKTEumg2sga7J7RJLRcT4mXg7YC2+yCqN
0Ma80j80Fh28IseiK920UiQlyI+BO/haaZJ9TJx2pH5B+qjnYOeqIShT7b+NP6nn
kwuo2BcCgYEAjO5EM0f9yuj9xsb49V7Gp3DiApxcThhUaF3am/YdHVhOYd9lk/dI
8NlJq73hvsGMerTn9DqCQ4kPmuOaPFbeBi7fJ5Shx6l1GVdTSSrBIg7oNRMok1ke
81vUauBtc0VtgmNn7R+1xvyoQKieQ38uXlC5NoLKelO0bbvvbTYQsEsCgYEAkvA6
u72mRVXubSy2Aa4R/yVjIjgmTa3YGCyrVl2zAshplb/KEfxjJkuuOo0FgpAzElHP
ZEFPalWMTdGwRjrvlVPFDpGvnJidY/g4iCdE0Wiut1Da3w8kI2aXqvsD+GhytlLX
qeFb//SaTwmUiCLfpPAx3DZJWAX4jm8Ku2wM/T8CgYEApGG2t6LtkqW8PcpjqHVh
cxkM0YfryfQ7EUFWBoKX8aR6mdb75rW9Usmilns1stiKU5SJzglJVfzz9az+ImYc
HRIYjDnmAYc3PjeSuEaA08gSzyQEjzoTc36pDRGG+nQz4Ko7gtjwsAyrG7OmIgp6
WXCiBfFNq5zF2tTut19GFqs=
-----END PRIVATE KEY-----
"""
client_email = "ma-19-407@onlimo.iam.gserviceaccount.com"
client_id = "114411866313456096870"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/ma-19-407%40onlimo.iam.gserviceaccount.com"
